resources:
  repositories:
    - repository: self
      checkoutOptions:
        clean: true
        fetchDepth: 5
        lfs: false

trigger:
  - master

name: Xmf2.Licences-CI-$(Date:yyyyMMdd)$(Rev:.r)

pool:
  vmImage: 'windows-latest'

steps:
  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      restoreSolution: 'Xmf2.Licences.sln'
      feedsToUse: 'select'

  - task: VSBuild@1
    displayName: Build Package
    inputs:
      solution: Xmf2.Licences.sln
      platform: 'any cpu'
      configuration: 'release'
      maximumCpuCount: true
    condition: succeeded()

  - task: NuGetCommand@2
    inputs:
      command: 'pack'
      packagesToPack: 'package.nuspec'
      versioningScheme: 'off'

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: drop"
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
    condition: succeeded()